DragonOS-Community/DragonOS

kernel/src/process/process.c, kernel/src/process/process.h, kernel/src/sched/cfs.c, kernel/src/sched/sched.c, kernel/src/sched/sched.h, kernel/src/syscall/syscall.c, kernel/src/syscall/syscall_num.h
bugfix:修复当使用sched()运行调度器，在切换进程的时候，由于不在中断上下文内，导致当前进程的上下文丢失的问题。
bugfix:修复切换进程的宏的汇编代码的损坏部分，未声明`rax`寄存器，从而导致的编译器未定义行为问题。
=> bugfix:修复调度器未完全保存进程上下文的问题；以及switch proc的汇编代码的undefined behaviour的问题

docs/kernel/locking/lockref.md, kernel/src/arch/x86_64/asm/cmpxchg.c, kernel/src/arch/x86_64/asm/cmpxchg.rs, kernel/src/arch/x86_64/asm/mod.rs, kernel/src/arch/x86_64/cpu.rs, kernel/src/arch/x86_64/include/asm/cmpxchg.h, kernel/src/lib.rs, kernel/src/libs/lockref.rs, kernel/src/libs/mod.rs, kernel/src/libs/spinlock.rs
- lockref文档
- Rust的RawSpinlock新增is_locked()和set_value()方法。
- new: Rust版本的lockref
- new:Rust封装cpu_relax(),通过pause指令，让cpu休息一会儿。降低空转功耗
=> 新增rust版本的lockref

kernel/src/libs/libUI/textui.c
修复由于textui加锁，更改了preempt_count导致“进程长时间连续输出字符”的情况下，进程调度器不运行的问题。
=> 修复由于textui加锁，更改了preempt_count导致“进程长时间连续输出字符”的情况下，进程调度器不运行的问题。

kernel/src/filesystem/fat/bpb.rs, kernel/src/filesystem/fat/fs.rs
https://github.com/DragonOS-Community/DragonOS/blob/45b8371173b070028457f7ee64be33f68b4f9ada/kernel/src/filesystem/fat/bpb.rs#L366
此处条件判断并不能有效区分FAT32和FAT12/16，导致了如果文件系统是FAT12/16的话， `validate()` 中的判断会走到 `kerror()`。
- 我所知的使用广泛的FAT类型的判断方法是根据簇的数量确定的。所以这里改成通过簇数确定FAT32还是FAT12/16。
- 另外将 `validate()` 往后移了，等到所有字段加载好了、FAT类型也判断好后再检查FAT32的BPB是否正确。
- [FAT Filesystem](http://elm-chan.org/docs/fat_e.html#fat_determination)
- [Microsoft FAT Specification](https://academy.cba.mit.edu/classes/networking_communications/SD/FAT.pdf)
=> 修正了FAT32判断逻辑，解决了文件系统为FAT12/16时系统无法正常启动的问题。

Makefile, tools/run-qemu.sh
改了一下Makefile和qemu运行脚本，可以通过make qemu时可以通过后缀-vnc来开启远程调试。
=> 添加了qemu使用VNC作为图像输出的选项

kernel/src/libs/lazy_init.rs, kernel/src/libs/mod.rs
新增lazy_init的功能，旨在解决lazy_static库不支持启用了`#![feature(associated_type_bounds)]`的对象的延迟初始化的问题。
=> new: lazy_init

kernel/src/driver/tty/mod.rs, kernel/src/driver/tty/tty_device.rs, kernel/src/filesystem/vfs/file.rs
解决了以下两个问题：
- 读取stdin的时候，遇到回车、EOF不会自动返回
- 对字符设备进行seek操作，没有返回`ESPIPE`的bug
=> 修复读取stdin时，无法正常读取的问题。

kernel/src/lib.rs, kernel/src/libs/align.rs, kernel/src/libs/int_like.rs, kernel/src/libs/mod.rs, tools/bootstrap.sh
这个pr包含了AlignedBox以及int_like宏。
AlignedBox 是一个用于分配对齐内存的结构体，它提供了一些对齐的宏和函数、结构体。分配的内存地址符合 ALIGN 的要求。如果类型 T 的对齐要求大于 ALIGN，则采用 T 的对齐要求。
AlignedBox 的原理是使用 Rust 的 core::alloc::Layout 结构体来分配内存。Layout 结构体描述了如何分配一块内存，包括大小、对齐方式等信息。在 AlignedBox 中，使用 Layout 结构体来描述分配内存的大小和对齐方式，然后使用 Rust 的全局内存分配器 GlobalAlloc 来分配内存。
AlignedBox 的功能是提供一种方便的方式来分配对齐内存。在某些情况下，需要分配对齐内存，例如在使用 SIMD 指令时，需要将数据对齐到指定的字节边界。AlignedBox 可以帮助用户方便地分配对齐内存，而不需要手动计算内存大小和对齐方式.
这部分是从redox里面借来的。
int_like 是一个 宏，用于定义一个新的类型，该类型是由一个整数类型（通常是 usize）支持的，但是不会影响安全性。
比如，把Pid定义为一个由usize支持的类型，同时定义AtomicPid是一个由AtomicUsize支持的类型。
int_like 宏的原理是使用 Rust 的 derive 宏来自动生成一些常用的 trait 实现，例如 PartialEq、Eq、PartialOrd、Ord、Debug、Clone 和 Copy。此外，它还使用 Rust 的 const fn 来定义一些常用的方法，例如 into 和 from，以便用户可以方便地将新类型转换为支持的整数类型。
int_like …
=> 添加AlignedBox和int_like宏

kernel/src/process/syscall.rs, user/libs/libc/src/include/export/unistd.h
=> 修复了wait4的异常报错

kernel/src/arch/x86_64/fpu.rs, kernel/src/exception/softirq.rs, kernel/src/mm/kernel_mapper.rs, kernel/src/mm/ucontext.rs
把除了自旋锁中的 local_irq_save 替换为了 IrqFlagsGuard。自旋锁和 _do_irqsoft 中的cli、sti没有替换
=>  替换 local_irq_save 为 IrqFlagsGuard 实现

kernel/src/libs/rwlock.rs, kernel/src/libs/spinlock.rs
1.修正rwlock有的地方由于未使用ManuallyDrop导致的use after free
2. spinlock守卫新增leak,spinlock新增force unlock功能.
=> 修正rwlock有的地方由于未使用ManuallyDrop导致的use after free && spinlock守卫新增leak,spinlock新增force unlock功能.

docs/introduction/build_system.md, tools/bootstrap.sh
1. 修复bootstrap.sh在安装libssl-dev之前，安装dadk，从而导致错误的问题
2. 构建系统的文档，补充对vnc端口的说明
=> 1. 修复bootstrap.sh在安装libssl-dev之前，安装dadk，从而导致错误的问题

kernel/src/filesystem/ramfs/mod.rs
为LockedRamFSInode实现了IndexNode中的相应方法：
- close方法：解决使用shell中的ls命令时报错
- open方法：解决在内存文件系统中打开或者创建文件时报错；
- truncate方法：解决使用fopen函数创建或者打开文件时返回空指针；
=> 修改RamFS目前存在的BUG

docs/kernel/debug/debug-kernel-with-gdb.md, docs/kernel/debug/index.rst, kernel/Cargo.toml
=> 添加rust-gdb调试内核文档

kernel/src/driver/net/e1000e/e1000e_driver.rs, kernel/src/lib.rs, kernel/src/libs/rwlock.rs, kernel/src/libs/wait_queue.rs, kernel/src/net/socket.rs, kernel/src/net/syscall.rs, kernel/src/process/idle.rs, kernel/src/process/mod.rs, kernel/src/sched/core.rs, tools/.gitignore, tools/create_hdd_image.sh, tools/run-qemu.sh
解决waitqueue sleep的时候,由于preempt count不为0,导致sched失败,从而导致该waitqueue下一次wakeup时,会把pcb多次加入调度队列的bug
=> Patch fix sched

docs/index.rst, docs/userland/appdev/c-cpp-quick-start.md, docs/userland/appdev/index.rst, docs/userland/appdev/rust-quick-start.md, tools/bootstrap.sh, user/Makefile
添加初始化DragonOS的Rust-Musl工具链的脚本.
- 之后DragonOS的默认应用程序将逐步切换到musl工具链上面，如果编译运行的时候出错，那么请重新运行bootstrap.sh即可
- 如果由于DADK版本升级导致无法编译的，这种情况是因为您使用的crates-io镜像站没有更新导致的。请直接使用`cargo install --git https://git.mirrors.dragonos.org/DragonOS-Community/DADK.git`更新dadk版本即可。
=> 添加初始化DragonOS的Rust-Musl工具链的脚本.

kernel/src/driver/base/block/block_device.rs, kernel/src/filesystem/fat/entry.rs, kernel/src/filesystem/vfs/syscall.rs
1. 修正文件open的时候可能错误的把inode清空的问题(如果当前inode是mknod创建的)
2. 修正fat和block device中,对文件写入部分的错误问题
=> 修正文件open和写入的错误

kernel/src/arch/x86_64/ipc/signal.rs, kernel/src/arch/x86_64/process/syscall.rs, kernel/src/arch/x86_64/syscall.rs, kernel/src/filesystem/vfs/core.rs, kernel/src/filesystem/vfs/file.rs, kernel/src/filesystem/vfs/mod.rs, kernel/src/filesystem/vfs/open.rs, kernel/src/filesystem/vfs/syscall.rs, kernel/src/filesystem/vfs/utils.rs, kernel/src/ipc/pipe.rs, kernel/src/ipc/signal_types.rs, kernel/src/lib.rs, kernel/src/process/exit.rs, kernel/src/process/mod.rs, kernel/src/process/syscall.rs, kernel/src/syscall/misc.rs, kernel/src/syscall/mod.rs, kernel/src/syscall/user_access.rs, kernel/src/time/syscall.rs
1. 新增以下系统调用
- SYS_LSTAT
- SYS_READV
- SYS_ACCESS
- SYS_UNLINK
- SYS_CHMOD
- SYS_FCHMOD
- SYS_UMASK
- SYS_SYSINFO
- SYS_CLOCK_GETTIME
- SYS_FCHMODAT
- SYS_FACCESSAT
2. 修改sys_wait4,使得其部分符合Linux的行为(还是有些地方不符合的,详情请对比linux-6.1.9的sys_wait4接口)
=> 新增系统调用，并对照linux-6.1.9改写sys_wait4

tools/create_hdd_image.sh, user/Makefile, user/dadk/config/tar_1_35.dadk
默认安装gnu tar到dragonos的/usr/bin目录下
该PR把最小的dadk版本提升到了0.1.5，默认情况下，应当会自动更新。
如果由于您使用的crates-io镜像更新的不够及时，导致编译失败，请使用以下命令安装：
```shell
cargo install --git https://git.mirrors.dragonos.org/DragonOS-Community/DADK.git --tag v0.1.5
```
=> 默认安装gnu tar到dragonos的/usr/bin目录下

kernel/src/arch/x86_64/mm/bump.rs, kernel/src/arch/x86_64/mm/mod.rs, kernel/src/driver/multiboot2/multiboot2.c, kernel/src/driver/multiboot2/multiboot2.h, kernel/src/link.lds, kernel/src/mm/allocator/buddy.rs, kernel/src/mm/allocator/bump.rs, kernel/src/mm/mod.rs, tools/write_disk_image.sh
解决方案:
1. 分区域把空闲页添加到buddy
2. 将内核链接到16M的位置,以避免uefi带来的内存空洞.
这个值是因为我看到linux的救援内核也是在16M的地址,因此猜测厂商不会使用这块内存.
尽管uefi规范讲的是固件可以采用任何地址,内核需要使用内核重定位技术去避免遇到内存空洞,但我没有这么做.
=> bugfix: 当物理机具有多个memory area的时候,无法正确使用这些区域的问题.以及在内核代码处出现内存空洞而导致无法正常运行的问题.

kernel/src/arch/x86_64/asm/entry.S, kernel/src/arch/x86_64/ipc/signal.rs, kernel/src/ipc/signal.rs, kernel/src/syscall/mod.rs, kernel/src/time/mod.rs, kernel/src/time/sleep.rs, user/dadk/config/nova_shell-0.1.0.dadk, user/dadk/config/relibc-0.1.0.dadk
原因是：
1. nanosleep函数对“spin/wait"方式等待的判断有误
2. nanosleep函数对定时器过期时间的计算有误，导致定时器过期过快，sleep失败
信号发送函数内，过早的把信号加入sigpending，应改为判断是否wants_signal之后再加入
syscall指令进入的系统调用，返回的时候没有do_signal导致的
原因是sigframe内的返回地址已经被弹出了，导致rsp加了8,而原来的relibc是在发起调用之前先push了一个u64到栈上，导致“刚好能跑”。现已修正relibc，使得这块的行为跟linux一致
=> bugfix: 修复无法sleep的问题以及进程处于block(true)状态时无法被信号唤醒&唤醒后不处理信号的问题

kernel/Cargo.toml, kernel/src/arch/riscv64/mm/mod.rs, kernel/src/arch/x86_64/mm/mod.rs, kernel/src/mm/early_ioremap.rs, kernel/src/mm/mod.rs, kernel/src/mm/no_init.rs
允许在内存管理初始化之前,使用fixmap功能,映射一些物理内存,并记录.
=> feature: 增加early io remap的fixmap功能

kernel/Cargo.toml
先前使用git仓库链接，现在由于sbi-rt包的新版本已发布至crates.io网站，使用crates提供的版本。本次只修改了Cargo.toml文件，Rust代码未被更改。
=> riscv: 更新sbi-rt至0.0.3版本

tools/bootstrap.sh, tools/build_gcc_toolchain.sh, tools/grub_auto_install.sh
1. archlinux上没有libssl-dev包，相对应的包名是openssl
2. zsh用户使用bootstrap.sh 会因为 source ~/.zshrc
导致bash执行很多zsh built-in 指令出现非常多错误
3. mkdir命令加-p选项避免对象目录存在时（反复执行脚本）报错
4. 修复简单错误(typo gcc 为 binutils)
5. 修复bootstrap.sh等脚本无法在非tools/目录执行的错误
=> tools/bootstrap.sh: 修复 archlinux and zsh 用户执行脚本时的报错

kernel/src/libs/wait_queue.rs
retain方法使用错了导致的bug，但是很离谱的一个点是为什么最近几个pr才会出问题。
=> 修改事件等待队列对于retain使用方法出错导致唤醒错误

env.mk, tools/build_gcc_toolchain.sh
由于archlinux 的 texinfo版本太新导致的gcc  #docs构建失败
使用 MAKEINFO=true 的make环境变量跳过gcc docs构建，绕过问题
修复make run时候遇到的编译user/apps时找不到指定工具链的问题
修复问题 #536
=> 修复Archlinux下的bootstrap脚本问题，

kernel/src/driver/base/cpu.rs, kernel/src/driver/base/device/mod.rs, kernel/src/driver/base/platform/platform_device.rs, kernel/src/driver/base/subsys.rs, kernel/src/driver/disk/ahci/ahcidisk.rs, kernel/src/driver/input/ps2_mouse/ps_mouse_device.rs, kernel/src/driver/input/serio/i8042/i8042_device.rs, kernel/src/driver/input/serio/i8042/i8042_ports.rs, kernel/src/driver/serial/serial8250/mod.rs, kernel/src/driver/tty/tty_device.rs, kernel/src/driver/video/fbdev/base/fbcon/mod.rs, kernel/src/driver/video/fbdev/base/fbmem.rs, kernel/src/driver/video/fbdev/vesafb.rs
Class里面存储的是设备的Arc，而Device又要求设备存储Class的Arc，这会导致循环引用，出现潜在的问题。
=> 把Device trait的set_class改为设置Weak指针，以避免循环引用问题。

kernel/src/net/socket/inet.rs
1.在udpsocket绑定端口的时候，检查绑定端口为0则绑定随机端口。
2.删除在write里检查端口为0的逻辑，应该在bind中检查，与tcpsocket相同。
=> fix udp bind

kernel/src/driver/tty/pty/unix98pty.rs, kernel/src/driver/tty/termios.rs, kernel/src/driver/tty/tty_core.rs, kernel/src/driver/tty/tty_device.rs, kernel/src/driver/tty/tty_driver.rs, kernel/src/driver/tty/tty_ldisc/ntty.rs, kernel/src/driver/tty/virtual_terminal/mod.rs, kernel/src/filesystem/vfs/file.rs, kernel/src/filesystem/vfs/syscall.rs
更完善pty，结果测试能够成功连接ssh，但是目前没有合适的sshd，感兴趣的同学可以试着移植redox-ssh
=> 完善pty，目前pty能够支持ssh

kernel/src/arch/x86_64/asm/apu_boot.S, kernel/src/arch/x86_64/asm/head.S, kernel/src/arch/x86_64/include/asm/apu_boot.h, kernel/src/arch/x86_64/interrupt/trap.rs, kernel/src/arch/x86_64/process/mod.rs, kernel/src/arch/x86_64/smp/mod.rs, kernel/src/init/initial_kthread.rs, kernel/src/ipc/pipe.rs, kernel/src/libs/lib_ui/textui.rs, kernel/src/libs/rwlock.rs, kernel/src/process/mod.rs, kernel/src/sched/mod.rs, kernel/src/smp/cpu/mod.rs, kernel/src/time/timer.rs
bugfix: 修复smp启动的时候，损坏0号核心的idle进程的内核栈的问题
=> bugfix: 修复smp启动的时候，损坏0号核心的idle进程的内核栈的问题

kernel/src/arch/x86_64/driver/apic/x2apic.rs, kernel/src/driver/base/device/bus.rs, kernel/src/driver/base/device/dd.rs, kernel/src/driver/base/device/driver.rs, kernel/src/driver/base/subsys.rs, kernel/src/driver/net/e1000e/e1000e_driver.rs, kernel/src/driver/net/mod.rs, kernel/src/driver/net/virtio_net.rs, kernel/src/driver/pci/pci.rs, kernel/src/driver/serial/serial8250/mod.rs, kernel/src/driver/virtio/mmio.rs, kernel/src/driver/virtio/mod.rs, kernel/src/driver/virtio/sysfs.rs, kernel/src/driver/virtio/transport.rs, kernel/src/driver/virtio/transport_pci.rs, kernel/src/driver/virtio/virtio.rs, kernel/src/filesystem/sysfs/mod.rs, kernel/src/net/mod.rs, kernel/src/net/net_core.rs, kernel/src/net/socket/inet.rs, tools/run-qemu.sh
- 在sysfs添加virtio总线
- 把virtio-net适配设备驱动模型
- 把virtio-net添加到sysfs
=> feat(driver): 把virtio添加到sysfs

user/apps/test-backlog/Makefile
=> fix(dog): 添加CC环境变量，解决编译时找不到musl-gcc的问题

kernel/src/sched/mod.rs, kernel/src/sched/syscall.rs, kernel/src/syscall/mod.rs
issue: https://github.com/DragonOS-Community/DragonOS/issues/756
=> feat(sched): add sched_yield

kernel/src/arch/riscv64/mm/mod.rs, kernel/src/arch/riscv64/process/idle.rs, kernel/src/arch/riscv64/process/mod.rs, kernel/src/arch/riscv64/process/syscall.rs, kernel/src/arch/riscv64/syscall/mod.rs, kernel/src/arch/x86_64/process/mod.rs, kernel/src/arch/x86_64/process/syscall.rs, kernel/src/arch/x86_64/syscall/mod.rs, kernel/src/init/initial_kthread.rs
refactor(process): Extract common logic for riscv and x86_64 in arch_switch_to_user to run_init_process
调整arch_switch_to_user函数，把riscv和x86_64的共用逻辑抽取出来。写成run_init_process函数，并且能够尝试运行多个不同的init程序，直到某个运行成功
=> refactor(process): 调整arch_switch_to_user函数，把riscv和x86_64的共用逻辑抽取出来。

.github/issue-checker.yml
The previous regex can not successfully match the pattern like `feat(driver/pci)`, which has a slash in the scope
=> ci: update the match regex of issue checker

kernel/src/arch/x86_64/driver/hpet.rs, kernel/src/driver/clocksource/timer_riscv.rs, kernel/src/driver/irqchip/riscv_intc.rs, kernel/src/time/timer.rs
fix: (riscv/timer): 修复riscv下没有更新墙上时钟以及没有处理软中断的bug
经过这个pr,riscv下，用户进程可以正常sleep
=> fix: (riscv/timer): 修复riscv下没有更新墙上时钟以及没有处理软中断的bug

kernel/src/mm/fault.rs, kernel/src/mm/ucontext.rs
修复了`VMA`结构体中的`mapped`标志没有被正确设置的错误
=> feat(mm): 修复vma映射标志错误

kernel/Cargo.toml, kernel/crates/bitmap/src/alloc_bitmap.rs, kernel/crates/bitmap/tests/alloc-bitmap.rs, kernel/src/arch/riscv64/asm/bitops.rs, kernel/src/arch/riscv64/driver/of.rs, kernel/src/arch/riscv64/interrupt/entry.rs, kernel/src/arch/riscv64/interrupt/handle.rs, kernel/src/arch/riscv64/interrupt/mod.rs, kernel/src/arch/riscv64/mm/mod.rs, kernel/src/arch/x86_64/driver/apic/lapic_vector.rs, kernel/src/driver/block/virtio_blk.rs, kernel/src/driver/clocksource/timer_riscv.rs, kernel/src/driver/irqchip/mod.rs, kernel/src/driver/irqchip/riscv_intc.rs, kernel/src/driver/irqchip/riscv_sifive_plic.rs, kernel/src/driver/net/virtio_net.rs, kernel/src/driver/virtio/irq.rs, kernel/src/driver/virtio/mod.rs, kernel/src/driver/virtio/sysfs.rs, kernel/src/driver/virtio/transport.rs, kernel/src/driver/virtio/transport_pci.rs, kernel/src/exception/handle.rs, kernel/src/exception/irqchip.rs, kernel/src/exception/irqdata.rs, kernel/src/exception/irqdesc.rs, kernel/src/exception/irqdomain.rs, kernel/src/exception/manage.rs, kernel/src/libs/cpumask.rs, kernel/src/mm/mmio_buddy.rs, kernel/src/smp/cpu/mod.rs
- 实现riscv plic驱动,能处理外部中断
- 能收到virtio-blk的中断
- 实现fasteoi interrupt handler
=> feat:(riscv/intr) 实现riscv plic驱动,能处理外部中断

kernel/src/arch/x86_64/driver/apic/apic_timer.rs
由于原先apic timer初始化的时候，先设置初始计数，然后才设置lvt，这导致在某些处理器上收不到apic timer的中断，从而没法调度。
经测试，本PR使得DragonOS在腾讯云的以下机型能够正常执行调度：
- SA2 (本PR之前，无法收到apic timer中断）
- S5 (本PR之前，无法收到apic timer中断）
- SA3 (本PR之前，无法收到apic timer中断）
- S6 (本PR之前，可以正常收到apic timer中断）
- SA4 (本PR之前，可以正常收到apic timer中断）
- S8 (本PR之前，可以正常收到apic timer中断）
注：由于云服务器上面pci驱动找不到mcfg表，导致无法正常初始化pci，因此上述截图是把pci初始化、磁盘驱动初始化注释掉，并且loop{}死循环在pid=1的内核线程的结果。符合预期。
=> fix(driver/apic_timer): 修复local apic timer初始化顺序导致的在某些云服务器上无法收到中断的bug

kernel/src/driver/acpi/pmtmr.rs, kernel/src/driver/clocksource/acpi_pm.rs, kernel/src/init/init.rs, kernel/src/time/clocksource.rs
This commit adjusts the timing of the setup_arch_post event to occur before the clocksource_boot_finish event, allowing the time subsystem to properly register architecture-specific clock sources.
=> chore: move setup_arch_post timepoint to before clocksource_boot_finish

kernel/src/time/timekeeping.rs
修复了一个时间减法先后顺序的逻辑bug，
https://github.com/DragonOS-Community/DragonOS/issues/816
=> fix(time):修复了issue #816内核时间子系统调用有误的bug

kernel/src/arch/x86_64/pci/pci.rs, kernel/src/filesystem/fat/fs.rs, kernel/src/filesystem/vfs/open.rs, kernel/src/filesystem/vfs/syscall.rs, kernel/src/lib.rs, kernel/src/syscall/mod.rs, kernel/src/time/mod.rs, user/apps/test_utimensat/.gitignore, user/apps/test_utimensat/Makefile, user/apps/test_utimensat/main.c, user/dadk/config/test_utimensat_0_1_0.dadk
impl sys_utimensat
impl sys_utimes
add utimensat test
fix some warning
=> feat(time): Add syscall support for utime*

kernel/src/net/event_poll/mod.rs, kernel/src/net/net_core.rs, kernel/src/net/socket/inet.rs, kernel/src/net/socket/mod.rs, kernel/src/net/socket/unix.rs, tools/Makefile
将epoll的wait_queue以及ep_items绑定到posix socket上。原先是绑定在smoltcp socket上，这对于listen的backlog这种情况，会有问题。
解决了问题：
- https://github.com/DragonOS-Community/DragonOS/issues/854
- https://github.com/DragonOS-Community/DragonOS/issues/853
=> fix: tcp poll没有正确处理posix socket的listen状态的问题

kernel/src/filesystem/eventfd.rs, kernel/src/filesystem/mod.rs, kernel/src/syscall/mod.rs, user/apps/test_eventfd/.gitignore, user/apps/test_eventfd/Makefile, user/apps/test_eventfd/main.c, user/dadk/config/test_eventfd_0_1_0.dadk
=> feat(fs): add eventfd syscall support

kernel/src/arch/x86_64/kvm/vmx/vcpu.rs, kernel/src/driver/disk/ahci/ahcidisk.rs, kernel/src/driver/disk/ahci/hba.rs, kernel/src/driver/disk/ahci/mod.rs, kernel/src/driver/net/loopback.rs, kernel/src/mm/mod.rs, tools/debugging/logmonitor/src/backend/monitor/mm.rs
refactor: 删除过时的va-pa转换函数，改为统一使用MMArch
=> refactor: 删除过时的va-pa转换函数，改为统一使用MMArch

Makefile, kernel/.cargo/config.toml, kernel/Makefile, kernel/env.mk, kernel/src/arch/riscv64/process/syscall.rs, kernel/src/arch/x86_64/process/syscall.rs, kernel/src/filesystem/vfs/open.rs, kernel/src/filesystem/vfs/syscall.rs, kernel/src/init/initial_kthread.rs, kernel/src/process/exec.rs, kernel/src/process/mod.rs, kernel/src/process/syscall.rs, kernel/src/syscall/mod.rs, kernel/src/syscall/user_access.rs
问题原因：写入用户栈、从用户空间读取的字符串，没有使用CString，导致问题。
=> fix: 修复由于升级到2024-07-23工具链之后，某些机器上面内核运行一直fault的问题。

kernel/src/driver/tty/tty_ldisc/ntty.rs, kernel/src/libs/keyboard_parser.rs
原本的代码里面，
- 当按下`Ctrl+c`的时候，输出的是`#`而不是`ETX`控制字。
- 当shift按下时，再按`Ctrl+c`，输出的是ETX，这也是不对的。（如果capslock激活，然后`ctrl+c`的话,那就无问题）
=> fix: 修复键盘码解析器没能正确处理类似ctrl C的控制字符的问题

kernel/src/filesystem/vfs/core.rs
使用 `rm` 工具删除时发现无法通过**相对路径**进行删除，提示找不到文件，但通过**绝对路径**或**当前目录位于根目录**可以成功删除
文件abc存在但提示未找到
排除了NovaShell的错误后，怀疑是内核有问题。查找后发现在`unlink`、`unlinkat`系统调用中使用的函数`do_unlink_at`中查找父目录的步骤中使用的路径为错误地使用了最开始传入的`path`参数，这会导致传入的参数`dirfd`为`AT_FDCWD`（指示使用当前目录）时函数会错误地在**根目录**使用**相对路径**进行查找导致无法找到文件进行删除
修正查找父目录时传入的路径参数，问题解决
=> fix: 修复do_unlink_at函数中的路径错误

kernel/src/filesystem/eventfd.rs, kernel/src/filesystem/vfs/file.rs, kernel/src/filesystem/vfs/syscall.rs, kernel/src/ipc/pipe.rs, user/apps/test_tokio/.gitignore, user/apps/test_tokio/Cargo.toml, user/apps/test_tokio/Makefile, user/apps/test_tokio/src/main.rs, user/dadk/config/test_tokio-0.1.0.dadk
修复了文件系统中的部分实现问题：
1. close系统调用存在死锁的问题
2. 为pipe文件实现`remove_epoll` 以和socket统一
3. 为eventfd 文件实现`kernel_ioctl` 和`remove_epoll`
=> feat: 增加tokio异步运行时支持

kernel/src/driver/base/block/block_device.rs, kernel/src/driver/base/block/disk_info.rs, kernel/src/driver/base/block/gendisk.rs, kernel/src/driver/base/block/manager.rs, kernel/src/driver/base/block/mod.rs, kernel/src/driver/block/virtio_blk.rs, kernel/src/driver/disk/ahci/ahcidisk.rs, kernel/src/driver/disk/ahci/mod.rs, kernel/src/driver/mod.rs, kernel/src/driver/pci/pci_irq.rs, kernel/src/driver/scsi/mod.rs, kernel/src/driver/virtio/irq.rs, kernel/src/filesystem/fat/bpb.rs, kernel/src/filesystem/fat/entry.rs, kernel/src/filesystem/fat/fs.rs, kernel/src/filesystem/mbr.rs, kernel/src/filesystem/vfs/core.rs, kernel/src/init/initial_kthread.rs
bbs链接：https://bbs.dragonos.org.cn/t/topic/332/3
剩余的2个任务我打算开新的PR来发。原因是：
- 要测试“整个磁盘作为gendisk”，需要kernel先支持qemu的[direct linux boot](https://qemu-project.gitlab.io/qemu/system/linuxboot.html)。
- 将磁盘和分区注册到devfs，功能较为独立，代码量比较多，为了控制当前这个PR的代码量，因此写到新的PR里面。
@xiaolin2004 麻烦看看
=> feat: 添加gendisk抽象

kernel/src/mm/page.rs, kernel/src/mm/ucontext.rs
文件映射的pr中完善了页表项保护位`EntryFlags`的生成机制，添加了保护位映射表，导致进行匿名可写映射时页表项的保护位为只读造成PageFault，但riscv64暂不支持缺页异常处理
在`from_prot_flags`方法中判断当前架构是否支持缺页异常，如果不支持就使用旧版的转换方法
=> fix(mm): 修复riscv64启动时的PageFault

kernel/src/libs/keyboard_parser.rs, user/dadk/config/nova_shell-0.1.0.dadk
修改了以下几个按键的字节码为xterm的字节码
- 上下左右
- home
- end
- del
- backspace
cc @GnoCiYeH 这个PR合并之后，https://github.com/DragonOS-Community/Held 需要做更改，不然跑不了。
更改的内容参考novashell的更改：
- https://github.com/DragonOS-Community/NovaShell/pull/46
- https://github.com/DragonOS-Community/NovaShell/pull/47
=> fix(kbd): 修复键盘命令解析器生成的字节码与Linux不一致的问题

kernel/src/driver/tty/tty_job_control.rs, kernel/src/driver/tty/tty_ldisc/ntty.rs, kernel/src/process/fork.rs, kernel/src/process/mod.rs, user/apps/test_sigint/.gitignore, user/apps/test_sigint/Makefile, user/apps/test_sigint/main.c, user/dadk/config/nova_shell-0.1.0.dadk, user/dadk/config/test_sigint-0.1.0.dadk
1. 为pcb添加了`sid`字段并初始化为0，将tty记录的会话初始化为当前pcb的sid（固定为0），并修改`job_ctrl_ioctl`函数中当前会话的判断逻辑，任意进程都被视为同一个会话从而允许设置前台进程组
2. tty记录的前台进程组`pgid`初始化为None，由NovaShell手动设置（否则如果tty记录的前台进程和当前进程不符的话会导致`tty_check_change`返回Err并无限循环，原理未知）
3. NovaShell启动时手动设置前台进程为shell，执行命令时将tty前台进程设置为子进程，子进程结束后再重新设置tty前台进程为shell
=> feat(tty): 实现发送SIGINT终止信号

kernel/src/driver/serial/serial8250/serial8250_pio.rs, kernel/src/driver/tty/termios.rs, kernel/src/driver/tty/tty_core.rs, kernel/src/driver/tty/tty_port.rs, kernel/src/driver/tty/virtual_terminal/mod.rs, kernel/src/driver/tty/virtual_terminal/virtual_console.rs, kernel/src/filesystem/eventfd.rs, kernel/src/filesystem/vfs/mount.rs, kernel/src/ipc/pipe.rs, kernel/src/net/event_poll/mod.rs, kernel/src/net/net_core.rs
- tty文件适配epoll，使epoll能够监听tty
- 修改串口handle_irq，原有每次只读取一个字节会导致：输入left(esc+[+A)被错误解析为(esc)+([)+(A)三个字符
- 为串口加上vcdata用于控制输入输出的格式问题（未解决，这个pr捎带）
=> feat(tty): 将tty设备适配epoll，修改串口部分问题

kernel/src/arch/x86_64/syscall/mod.rs, kernel/src/driver/base/block/block_device.rs, kernel/src/driver/base/device/mod.rs, kernel/src/driver/base/kobject.rs, kernel/src/driver/base/platform/platform_device.rs, kernel/src/driver/base/uevent/mod.rs, kernel/src/driver/block/virtio_blk.rs, kernel/src/driver/net/class.rs, kernel/src/driver/net/virtio_net.rs, kernel/src/driver/pci/raw_device.rs, kernel/src/driver/pci/test/pt_device.rs, kernel/src/driver/rtc/class.rs, kernel/src/driver/rtc/sysfs.rs, kernel/src/driver/tty/sysfs.rs, kernel/src/driver/video/fbdev/base/fbcon/mod.rs, kernel/src/driver/video/fbdev/base/fbmem.rs, kernel/src/exception/sysfs.rs
- 新增 CommonAttrGroup，由于uevent是所有设备都共有的属性文件，为了解耦和可拓展，新增了通用属性组，并为大部分的设备类型添加
- 目前支持 sysfs下 block, char, Net, rtc, tty等类型设备的 uevent 文件读操作
=> feat: 支持 sysfs下 block, char, Net, rtc, tty 等类型设备的 uevent 文件读操作

kernel/src/filesystem/vfs/core.rs, kernel/src/filesystem/vfs/syscall.rs, kernel/src/syscall/mod.rs
将内核原本实现的do_mkdir_at暴露出来,实现SYS_MKDIRAT
解决了：https://github.com/DragonOS-Community/DragonOS/issues/983
在添加这个系统调用后，`cp -r`已经能正常工作
r? @val213
=> feat: 添加SYS_MKDIRAT系统调用

kernel/src/process/fork.rs, kernel/src/process/mod.rs
临时解决了：https://github.com/DragonOS-Community/DragonOS/issues/981
@smallcjy @1037827920
=> fix: 临时修复线程退出时处理tty前台进程组产生panic的bug

kernel/src/driver/tty/kthread.rs
=> fix: tty刷新线程初始化之前，键盘产生数据导致崩溃的问题

kernel/Cargo.toml, kernel/src/arch/x86_64/asm/entry.S, kernel/src/driver/input/mod.rs, kernel/src/driver/input/serio/i8042/mod.rs, kernel/src/driver/keyboard/ps2_keyboard.rs
开机的时候，在初始化完成之前，连续一直敲键盘，然后移动了一下鼠标，就能触发原本的bug：开机之后shell输入不了东西，但cpu中断是开的。
暂时通过条件编译的方式解决. 目前认为是鼠标驱动问题,没有正确判断是不是自己的数据...
但是因为我们场景下,鼠标驱动几乎用不到,因此先条件编译屏蔽.
=> fix: 临时修复键盘驱动与鼠标驱动冲突导致键盘无响应

kernel/src/driver/tty/virtual_terminal/virtual_console.rs, kernel/src/libs/font/mod.rs
bug复现方法:
在commit [37c2359](https://github.com/DragonOS-Community/DragonOS/commit/37c2359ac400be9a77c26542bd60ef8267aa5ee6) 下，
x86_64，调整head.S，把图形窗口设置成640*400,然后启动dragonos.
接着shell自动补全（按tab键）：
在这里已经卡了，backtrace会发现内核已经panic。
=> fix(tty): 修复tty对tab进行处理时产生数组越界panic的问题

kernel/src/driver/block/virtio_blk.rs, kernel/src/driver/net/virtio_net.rs, kernel/src/driver/virtio/transport.rs, kernel/src/driver/virtio/transport_pci.rs, kernel/src/net/net_core.rs
**PR描述**
- 修改了pci transport的中断初始化位置
- 在dhcp请求之间加入适当的睡眠
相关issue：#1007
=> fix(driver/virtio): 修改pci transport中断初始化的位置

user/dadk/config/nova_shell-0.1.0.dadk
[修复执行前台命令时未设置前台进程的错误 #51](https://github.com/DragonOS-Community/NovaShell/pull/51)
=> chore: Update NovaShell to cb835e03e4

kernel/src/arch/riscv64/process/syscall.rs, kernel/src/arch/x86_64/process/syscall.rs, kernel/src/process/syscall.rs
cc @val213  @sparkzky @MemoryShore
=> fix: 修复了do execve 加载程序失败时,没能正确返回错误码给用户态的问题

.github/workflows/docs-multiversion.yml
=> ci: 推送文档到s3时，不同步`p/*`目录下的文件

kernel/Cargo.toml, kernel/Makefile, kernel/src/Makefile, kernel/src/arch/riscv64/link.ld, kernel/src/arch/riscv64/riscv64gc-unknown-none-elf.json, kernel/src/arch/riscv64/syscall/mod.rs, kernel/src/arch/x86_64/link.lds, kernel/src/arch/x86_64/syscall/mod.rs, kernel/src/arch/x86_64/x86_64-unknown-none.json, kernel/src/lib.rs, kernel/src/syscall/mod.rs
使用新的unwinding库应该可以解决发生的链接错误，同时这个库会正确地释放资源，支持常见的架构。
我关闭了Makefile中的一个检查，因为这个unwinding库中引入了`eh_personality`，但是cargo clippy会说标准库已经存在，因为kernel使用的工具链是*-linux-gnu。 我暂时不确定这个地方这么去掉这个冲突。
=> feat: update to new backtrace lib

kernel/src/process/mod.rs, kernel/src/sched/clock.rs, kernel/src/sched/cputime.rs, kernel/src/sched/mod.rs
解决了 https://github.com/DragonOS-Community/DragonOS/issues/1047 发生panic的问题。
但是，仍然存在问题：
按照 https://github.com/DragonOS-Community/DragonOS/issues/1047 的方法尝试，当问题复现时，可以注意到，是卡了一下子，然后输出panic信息。
本pr改完之后，按照 https://github.com/DragonOS-Community/DragonOS/issues/1047 进行尝试，不会panic，但是问题触发时，会卡一下，然后完全卡死。gdb看到在idle进程。
因此怀疑是调度有点问题？
@GnoCiYeH @val213
=> fix: 修正进程pcb的`on_cpu`字段未设置导致的panic问题

kernel/src/ipc/pipe.rs, user/apps/test_fifo_write/Makefile, user/apps/test_fifo_write/main.c, user/dadk/config/test_fifo_write_0_1_0.toml
测试结果：
**期望情况**
非阻塞模式下
```
========== Testing Nonblocking Mode ==========
--- Testing: No readers (FIFO never had readers) (nonblocking=1) ---
Result: Failed to open FIFO for writing (ENXIO: No readers).
--- Testing: Reader exists but disconnects (nonblocking=1) ---
Result: Write failed with EPIPE (no readers available).
--- Testing: Active reader exists (nonblocking=1) ---
Result: Write succeeded. Bytes written: 13
```
阻塞模式下
```
========== Testing Blocking Mode ==========
--- Testing: No readers (FIFO never had readers) (nonblocking=0) ---
Result: Failed to open FIFO for writing (ENXIO: No readers).
--- Testing: Reader exists but disconnects (nonblocking=0) ---
Result: Write failed with EPIPE (no readers available).
--- Testing: Active reader exists (nonblocking=0) ---
Result: Write …
```
=> fix:命名管道读行为不符合posix规范问题

kernel/src/process/mod.rs
会导致http server被kill时,pcb没有drop
=> fix: 解决进程退出时没有主动释放fdtable的问题

kernel/src/driver/net/mod.rs, kernel/src/net/net_core.rs, kernel/src/net/socket/common/shutdown.rs, kernel/src/net/socket/inet/common/mod.rs, kernel/src/net/socket/inet/stream/inner.rs, kernel/src/net/socket/inet/stream/mod.rs
The miss activation after close of TCP cause system panic at network interupt arrive, though which should be ignored.
Now the behavior still kind of weird, the first query to the virtio "reset" after a short period of time, but the following query after the first one is immediate reset. Also, the default "reset" behavior seems not the correct behavior when you access a "non exist" server. Need further investegation.
The UDP socket seems not correctly closed.
TCP socket still couldn't connect a remote socket.
The test case "test-backlog" with actix-web runtime is still unable to run.
=> fix: TCP socket miss activation after close

kernel/src/init/initial_kthread.rs, kernel/src/ipc/signal.rs, kernel/src/process/fork.rs, kernel/src/process/kthread.rs, kernel/src/syscall/mod.rs
- 修复`copy_process`函数对标志位处理不正确的bug
- init进程搜索列表中,支持为默认init程序传入参数
=> fix(process): 修复copy_process的一些bug & 支持默认init进程传参

.gitignore, kernel/src/time/timer.rs
修复split_pos 初始值错误导致原本应该被插入到链表末尾的定时器,插入到了链表头
=> fix: 在插入新的timer时,边界条件判断不正确的问题

kernel/src/driver/tty/tty_ldisc/ntty.rs
修复了一次性在栈上分配8K的问题（内核栈才16K）
改为Box::new之后，按照rust的rfc1909: https://github.com/rust-lang/rfcs/blob/master/text/1909-unsized-rvalues.md 就不会栈上分配了。
=> fix: 修复nttyData的buffer导致初始化时,栈溢出的问题

kernel/crates/rust-slabmalloc/src/lib.rs, kernel/crates/rust-slabmalloc/src/pages.rs, kernel/crates/rust-slabmalloc/src/sc.rs, kernel/crates/rust-slabmalloc/src/tests.rs, kernel/crates/rust-slabmalloc/src/zone.rs, kernel/src/mm/allocator/kernel_allocator.rs, kernel/src/mm/allocator/slab.rs
- 新增 `tests.rs` 模块，包含多个测试用例以验证内存分配器的正确性和性能。
- 优化 `pages.rs` 中的 `Bitfield` 实现，移除不必要的 `get_offset_for_align` 函数。
- 在 `zone.rs` 中新增 `try_reclaim_pages_in_slab` 方法，用于在特定 slab 中回收页面。
- 修复 `kernel_allocator.rs` 中的 `allocator_select_condition` 逻辑，移除对 `slab_init_state` 的依赖。
- 移除 `slab.rs` 中的 `slab_init_state` 函数，简化初始化状态检查。
=> fix: 修复slab分配器的UAF\内存越界问题

kernel/src/driver/net/irq_handle.rs, kernel/src/driver/net/kthread.rs, kernel/src/driver/net/mod.rs, kernel/src/driver/net/virtio_net.rs, kernel/src/net/net_core.rs, kernel/src/net/socket/inet/common/mod.rs, kernel/src/net/socket/inet/datagram/mod.rs, kernel/src/net/socket/inet/stream/inner.rs
=> feat(net): 引入kthread，将Inet-网卡处理流程移入内核线程中

tools/bootstrap.sh
- 修改bootstrap.sh的成功的banner: `make run`为`make run-nographic`以适应新需求。
- 优化rust组件安装逻辑，调整`cargo-binutils`和`bpf-linker`的安装位置，确保工具链配置正确。
=> fix(tools): 调整bootstrap.sh脚本中的banner和依赖安装顺序

kernel/crates/asm_macros/src/lib.rs, kernel/crates/asm_macros/src/loongarch64/context.rs, kernel/crates/asm_macros/src/loongarch64/mod.rs, kernel/src/arch/loongarch64/asm/mod.rs, kernel/src/arch/loongarch64/cpu.rs, kernel/src/arch/loongarch64/init/boot.rs, kernel/src/arch/loongarch64/init/mod.rs, kernel/src/arch/loongarch64/interrupt/entry.rs, kernel/src/arch/loongarch64/interrupt/handle.rs, kernel/src/arch/loongarch64/interrupt/mod.rs, kernel/src/arch/loongarch64/link.ld
- 栈保存&恢复
- 开机时临时设置异常处理程序,并验证可进入异常处理程序 (通过临时编写break 0 的asm是可以验证能进入do_reserved_())
汇编代码借鉴了linux 6.6.21的。
todo: 接下来会在后续的pr逐步完善la64启动时的异常、中断处理功能（与linux保持一致）
=> feat(la64): 实现了较为早期的la64的异常处理的注册

kernel/Cargo.lock, kernel/Cargo.toml
将loongArch64依赖从git版本切换为crates.io注册表版本0.2.5，
=> chore: 更新loongArch64依赖版本至0.2.5

kernel/Cargo.lock, kernel/Cargo.toml, kernel/src/debug/tracing/tracepoint.rs, kernel/src/driver/input/ps2_mouse/ps_mouse_device.rs, kernel/src/driver/keyboard/ps2_keyboard.rs, kernel/src/filesystem/devfs/mod.rs, kernel/src/filesystem/devfs/null_dev.rs, kernel/src/filesystem/devfs/zero_dev.rs, kernel/src/filesystem/devpts/mod.rs, kernel/src/filesystem/fat/fs.rs, kernel/src/filesystem/kernfs/mod.rs, kernel/src/filesystem/procfs/mod.rs, kernel/src/filesystem/ramfs/mod.rs, kernel/src/filesystem/vfs/fcntl.rs, kernel/src/filesystem/vfs/mod.rs, kernel/src/filesystem/vfs/mount.rs, kernel/src/filesystem/vfs/stat.rs, kernel/src/filesystem/vfs/syscall.rs, kernel/src/filesystem/vfs/vcore.rs, kernel/src/init/init.rs, kernel/src/init/initial_kthread.rs, kernel/src/ipc/pipe.rs, kernel/src/syscall/mod.rs, kernel/src/time/mod.rs, kernel/src/virt/vm/kvm_dev.rs
refactor(vfs): 重构statx系统调用的实现
- 将kstat的获取,与posix statx的获取进行分离.
- 修复statx没有处理dirfd的bug
- 在Metadata结构体中新增btime字段，表示文件的创建时间
- 更新多个文件系统的metadata实现，添加对btime的支持
- 引入derive_builder crate以简化Metadata构建过程
- 重构vfs模块，将core重命名为vcore以避免命名冲突
- 实现vfs_statx和vfs_getattr函数，支持更详细的文件属性查询
- 新增LookUpFlags定义，用于路径查找时的标志位
=> refactor: 重构statx的实现

kernel/src/arch/x86_64/mm/fault.rs, kernel/src/driver/base/device/driver.rs, kernel/src/driver/char/virtio_console.rs, kernel/src/driver/pci/pci.rs, kernel/src/driver/tty/tty_ldisc/mod.rs, kernel/src/driver/virtio/sysfs.rs, kernel/src/filesystem/page_cache.rs, kernel/src/mm/fault.rs, kernel/src/mm/page.rs, kernel/src/mm/ucontext.rs
经过此commit,用户程序可以直接mmap文件然后读写（无需通过read/write去读取）
~~目前这个pr仍然有bug：对同一文件的第二次filemap，会在读取的时候直接panic掉。~~
25.5.10： 已经解决： https://github.com/DragonOS-Community/DragonOS/pull/1158/commits/20cdd279a50c5e4d7d6a25e9430aac6df2660351
`test_filemap.c`
```c
#include <ctype.h>
#include <fcntl.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/mman.h>
#include <sys/stat.h>
#include <unistd.h>
#define EXPECTED_LEN 6 // "hello"的长度 + \0
int main() {
printf("Program started\n");
const char *filename = "testfile";
int fd;
struct stat st;
char *mapped;
printf("Attempting to open file: %s\n", filename);
fd = open(filename, O_RDWR);
if (fd == -1) {
perror("open failed");
exit(EXIT_FAILURE);
}
printf("File opened successfully\n");
printf("Getting file stats\n");
if (fstat(fd, &st) == -1) { …
```
=> fix(page_cache): 修复pagecache无法直接mmap然后读写文件的bug

kernel/src/time/sleep.rs, kernel/src/time/timer.rs
在sleep和schedule_timeout模块中增加信号中断检查，当定时器被信号中断时取消定时器并返回ERESTARTSYS错误。
解决了 https://github.com/DragonOS-Community/DragonOS/issues/1163
=> fix(time): 处理信号中断导致的定时器唤醒

Makefile, kernel/src/process/mod.rs
修改KernelStack的SIZE和ALIGN常量值，将内核栈大小从16KB增加到32KB。
因为内核有些地方16k会爆栈，尤其是rv64
=> refactor(kernel): 增加内核栈大小从0x4000到0x8000

kernel/src/arch/x86_64/mm/fault.rs, kernel/src/process/syscall/sys_fork.rs, kernel/src/process/syscall/sys_vfork.rs, kernel/src/syscall/mod.rs
同时,将sys_fork\sys_vfork调整为使用syscall table机制来实现
解决了 https://github.com/DragonOS-Community/DragonOS/issues/1191
cc @sparkzky  @dolzhuying
=> fix: 解决syscall_table处理结束后,忘记执行调度的bug

kernel/src/filesystem/poll.rs, kernel/src/filesystem/vfs/syscall/mod.rs, kernel/src/filesystem/vfs/syscall/sys_pselect6.rs, kernel/src/filesystem/vfs/syscall/sys_select.rs, kernel/src/lib.rs, user/apps/test_select/Makefile, user/apps/test_select/main.c, user/dadk/config/test_select_0_1_1.toml
=> feat: add select and pselect6 syscall

kernel/src/driver/tty/pty/unix98pty.rs, kernel/src/filesystem/devfs/mod.rs, kernel/src/filesystem/fs.rs, kernel/src/filesystem/overlayfs/mod.rs, kernel/src/filesystem/procfs/mod.rs, kernel/src/filesystem/sysfs/mod.rs, kernel/src/filesystem/vfs/mod.rs, kernel/src/filesystem/vfs/mount.rs, kernel/src/filesystem/vfs/open.rs, kernel/src/filesystem/vfs/syscall/mod.rs, kernel/src/filesystem/vfs/syscall/sys_mount.rs, kernel/src/filesystem/vfs/syscall/sys_umount2.rs, kernel/src/filesystem/vfs/utils.rs, kernel/src/filesystem/vfs/vcore.rs, kernel/src/process/namespace/mnt.rs, kernel/src/process/namespace/mod.rs, kernel/src/process/namespace/nsproxy.rs, kernel/src/process/stdio.rs
Add initial mount namespace functionality with root namespace creation:
- Create root mount namespace initialization and management
- Implement basic mount namespace structure with root mountfs
- Add namespace-aware mount/umount operations and VFS modifications
- Update filesystem modules (devfs, procfs, sysfs, overlayfs) for namespace compatibility
- Modify TTY and stdio for namespace support
**Note: This implementation only creates the root namespace. Management of multiple mount namespace hierarchies and propagation relationships will be implemented in subsequent PRs.**
=> feat: implement basic mount namespace support

user/dadk/config/nova_shell-0.1.0.toml
将NovaShell的git revision从d7d2136c5a更新为25dce88
=> chore: 更新NovaShell的git revision版本为25dce88

kernel/crates/bitmap/src/lib.rs, kernel/crates/bitmap/src/static_bitmap.rs, kernel/crates/bitmap/src/traits.rs, kernel/crates/bitmap/tests/static-bitmap.rs, kernel/src/driver/block/virtio_blk.rs, kernel/src/driver/char/virtio_console.rs, kernel/src/driver/clocksource/timer_riscv.rs, kernel/src/driver/scsi/mod.rs, kernel/src/driver/tty/tty_ldisc/ntty.rs, kernel/src/driver/tty/virtual_terminal/virtual_console.rs, kernel/src/mm/no_init.rs, tools/debugging/logmonitor/src/lib.rs
- 移除generic_const_exprs特性依赖
- 引入static_bitmap_size常量函数和static_bitmap!宏
- 修改StaticBitmap结构体定义
- 更新相关测试和使用代码
修改的原因是这个特性在rust编译器里面是未完成的状态，并且升级dragonos的工具链的时候卡到这个bug了
https://github.com/rust-lang/rust/issues/76560
=> refactor(bitmap): 重构静态位图实现，移除incomplete_features依赖

.github/workflows/makefile.yml, build-scripts/Cargo.lock, build-scripts/kernel_build/Cargo.toml, build-scripts/kernel_build/src/lib.rs, build-scripts/kernel_build/src/version_gen.rs, kernel/.gitignore, kernel/Cargo.lock, kernel/src/Makefile, kernel/src/filesystem/procfs/mod.rs, kernel/src/filesystem/procfs/proc_version.rs, kernel/src/init/.gitignore, kernel/src/init/init.rs, kernel/src/init/mod.rs, kernel/src/process/namespace/uts_namespace.rs, user/apps/about/Makefile, user/apps/about/about.c
添加了内核构建时自动生成版本信息的功能，包括版本号、构建时间、编译器信息、Git提交等。
在内核启动时打印版本信息，并可通过/proc/version文件查询。更新了about应用使用uname系统调用
=> feat(build, kernel): 添加内核版本信息生成与显示功能

kernel/src/libs/futex/futex.rs
- 当futex键不存在时，不再返回EINVAL错误，而是创建新的FutexHashBucket
=> fix(futex): 修复futex键不存在时的错误处理

docs/kernel/ipc/index.rst, docs/kernel/ipc/ipc_namespace.md, kernel/src/ipc/shm.rs, kernel/src/ipc/syscall/sys_shmat.rs, kernel/src/ipc/syscall/sys_shmctl.rs, kernel/src/ipc/syscall/sys_shmget.rs, kernel/src/mm/init.rs, kernel/src/mm/page.rs, kernel/src/mm/ucontext.rs, kernel/src/process/namespace/ipc_namespace.rs, kernel/src/process/namespace/mod.rs, kernel/src/process/namespace/nsproxy.rs, user/apps/r_unitest/Cargo.lock, user/apps/r_unitest/src/bin/test_ipc_ns_shm.rs
- 添加IpcNamespace结构体并集成到NsProxy中
- 将全局SHM_MANAGER重构为per-ns ShmManager
- 修改shm相关系统调用以支持命名空间隔离
- 添加VMA的shm_id字段用于精确维护映射计数
- 新增IPC命名空间测试用例
- 更新相关文档
=> feat(ipc): 实现IPC命名空间初步支持

user/apps/tests/syscall/gvisor/blocklists/chdir_test, user/apps/tests/syscall/gvisor/runner/src/lib_sync.rs, user/apps/tests/syscall/gvisor/whitelist.txt
- Add chdir_test to blocklists
- Fix formatting of gtest_filter argument in test runner
- Enable chdir_test in whitelist
=> test(gvisor): add chdir_test and fix test runner filter formatting

kernel/src/filesystem/fat/fs.rs, kernel/src/filesystem/page_cache.rs, kernel/src/filesystem/vfs/file.rs, kernel/src/filesystem/vfs/syscall/mod.rs, kernel/src/filesystem/vfs/syscall/sys_truncate.rs, kernel/src/filesystem/vfs/vcore.rs, user/apps/c_unitest/test_truncate.c
- 添加VFS层的统一vfs_truncate封装，包含文件类型和只读挂载检查
- 实现truncate系统调用处理，支持路径解析和符号链接跟随
- 修复FAT文件系统resize方法，确保页缓存和元数据同步更新
- 添加全面的用户空间测试用例，覆盖各种边界条件和错误情况
- 优化文件截断流程，统一通过VFS封装处理类型和只读检查
=> feat(filesystem): 实现truncate系统调用
