DragonOS-Community/DragonOS

docs/introduction/build_system.md
按照文档拉取 Error response from daemon: manifest for dragonos/dragonos-dev:latest not found: manifest unknown: manifest unknown 缺少版本
=> 修改pull docker镜像

.gitignore, .vscode/settings.json, kernel/common/math/pow.c, kernel/filesystem/fat32/fat_ent.c
将 `kernel\common\math\pow.c` 的求幂运算优化为快速幂
=> 优化了数学库中的pow.c

user/apps/shell/shell.c, user/libs/libKeyboard/keyboard.c
=> Patch add shell history

user/apps/shell/shell.c, user/libs/libKeyboard/keyboard.c
=> Patch add shell history(update for issue #23)

kernel/lib/libUI/textui.c
=> 修复输出\b后未修改背景的错误

.github/workflows/makefile.yml
=> Revert "Update makefile.yml"

docs/kernel/process_management/index.rst, docs/kernel/process_management/pcb.md, kernel/src/process/proc-types.h, kernel/src/process/process.c, kernel/src/process/process.h, kernel/src/syscall/syscall.c
=> bugfix: 修复进程pcb被回收时，未将其从链表中删除的问题

.gitignore, tools/.gitignore, tools/arch/i386/bios/grub/.gitkeep, tools/arch/i386/efi/grub/.gitkeep, tools/arch/x86_64/efi/grub/.gitkeep, tools/grub_auto_install.sh, tools/write_disk_image.sh
1、bugfix: 修复编译grub的脚本的部分错误
2、将grub下载源替换为tuna
3、优化写入磁盘镜像的脚本
4、将`bios`文件夹改名为`legacy`
=> 调整编译grub的脚本的部分

kernel/src/include/bindings/wrapper.h, kernel/src/libs/mod.rs, kernel/src/libs/rwlock.rs, kernel/src/process/process.c, kernel/src/sched/cfs.rs, kernel/src/sched/core.rs, kernel/src/sched/rt.rs, kernel/src/smp/smp.c, kernel/src/smp/smp.h
=> Patch cpu loads

docs/community/ChangeLog/V0.1.x/V0.1.6.md, docs/community/ChangeLog/index.rst, docs/introduction/build_system.md, docs/introduction/features.md, tools/bootstrap.sh, user/apps/about/about.c
=> V0.1.6发行日志&更新构建系统文档

Makefile
=> Makefile: 根目录下添加make help命令

tools/build_gcc_toolchain.sh
fix some build script bugs
add arch linux prerequisited packages
=> fix some script bugs

kernel/src/arch/x86_64/include/asm/cmpxchg.h, kernel/src/common/atomic.h
fix arch_try_cmpxchg in atomic_cmpxchg
=> fix arch_try_cmpxchg macro declaration

kernel/src/arch/x86_64/process/mod.rs, kernel/src/ipc/signal.rs, kernel/src/ipc/signal_types.rs, kernel/src/process/fork.rs, kernel/src/process/initial_proc.rs, kernel/src/process/mod.rs
将新的pcb中的内容分类，分别加锁
麻烦@GP-Bullet 看看哈哈
=> 将新的pcb中的内容分类，分别加锁

kernel/src/filesystem/fat/entry.rs, kernel/src/filesystem/fat/fs.rs, kernel/src/filesystem/vfs/fcntl.rs, kernel/src/filesystem/vfs/file.rs, kernel/src/filesystem/vfs/mod.rs, kernel/src/filesystem/vfs/syscall.rs, kernel/src/libs/elf.rs, kernel/src/mm/syscall.rs, kernel/src/syscall/mod.rs, user/Makefile, user/apps/test_sqlite3/.gitignore, user/apps/test_sqlite3/Makefile, user/apps/test_sqlite3/main.c, user/dadk/config/test_sqlite3-3.42.0.dadk
- 移植sqlite3
- 增加fcntl系统调用
- bugfix: 修正fat文件系统未能正确的扩展文件大小的bug
- 修正brk系统调用不符合规范的地方
- bugfix: 程序加载器映射内存时，计算要映射的大小不正确的问题。
=> 移植sqlite3,并修复一些bug

.github/workflows/rustfmt.yml, Cargo.toml, Makefile, docs/introduction/build_system.md, kernel/Makefile, kernel/src/Makefile, rust-toolchain.toml, user/Makefile, user/apps/Makefile, user/libs/Makefile, user/libs/libc/Makefile
=> 解决设置rust workspace带来的“工具链不一致”的问题

docs/introduction/build_system.md, tools/bootstrap.sh
=> fix: DragonOS-Community/DragonOS#358

kernel/src/driver/pci/pci_irq.c, kernel/src/driver/timers/HPET/HPET.c, tools/build_gcc_toolchain.sh
memory leak, wrong irq_name allocation length in pci_irq.c
add function declaration to avoid compiling warning
add extra packages need for build
=> fix a couple of problems

kernel/src/driver/pci/pci_irq.c
=> fix compiler warnings in pci_irq.c

kernel/src/debug/Makefile, kernel/src/debug/kallsyms.c
include rust symbols in kallsyms
=> use demangled names

kernel/src/arch/x86_64/interrupt/mod.rs, kernel/src/arch/x86_64/process/mod.rs, kernel/src/head.S, kernel/src/process/kthread.rs, kernel/src/process/mod.rs, kernel/src/sched/cfs.rs, kernel/src/sched/syscall.rs
1. 修正由于init proc union导致的无法运行的问题
2. 修正由于内核线程启动后默认sleep的行为导致init进程无法正常运行的bug
=> 修正由于init proc union导致的无法运行的问题 && 修正由于内核线程启动后默认sleep的行为导致init进程无法正常运行的bug

kernel/Cargo.toml, kernel/src/driver/acpi/acpi.c, kernel/src/driver/acpi/bus.rs, kernel/src/driver/acpi/c_adapter.rs, kernel/src/driver/acpi/mod.rs, kernel/src/driver/acpi/sysfs.rs, kernel/src/driver/base/device/bus.rs, kernel/src/driver/base/kobject.rs, kernel/src/driver/base/kset.rs, kernel/src/driver/multiboot2/multiboot2.c, kernel/src/driver/multiboot2/multiboot2.h, kernel/src/filesystem/kernfs/mod.rs, kernel/src/filesystem/sysfs/file.rs, kernel/src/filesystem/sysfs/mod.rs, kernel/src/filesystem/vfs/syscall.rs, kernel/src/main.c, kernel/src/mm/c_adapter.rs, kernel/src/mm/mmio.h, kernel/src/mm/mmio_buddy.rs
bugfix: multiboot2启动的信息因为没及时转存导致后面无法从其中进行查询的bug
feature: 把acpi表、acpi bus加入sysfs
=> 在Sysfs中引入ACPI Firmware

kernel/src/arch/x86_64/acpi.rs, kernel/src/arch/x86_64/c_adapter.rs, kernel/src/arch/x86_64/mod.rs, kernel/src/arch/x86_64/setup.rs, kernel/src/arch/x86_64/smp/mod.rs, kernel/src/driver/acpi/mod.rs, kernel/src/driver/base/cpu.rs, kernel/src/driver/base/device/bus.rs, kernel/src/driver/base/device/mod.rs, kernel/src/driver/base/init.rs, kernel/src/driver/base/mod.rs, kernel/src/driver/base/platform/platform_device.rs, kernel/src/main.c
1. 启动时从acpi获取所有的cpu信息并存到SMP_BOOT_DATA
2. 注册cpu subsystem/bus到sysfs(暂时未添加内容)
todo:
1. build_cpu_map(在X86_64SmpManager中)
2. 实现cpu mask
3. 把cpu设备注册到sysfs
=> 初步编写cpu信息获取的代码

kernel/src/driver/base/block/block_device.rs, kernel/src/filesystem/fat/fs.rs, kernel/src/filesystem/vfs/file.rs, user/dadk/config/dragon_reach-0.1.0.dadk, user/libs/libc/src/Makefile
- 修复block_device中read_at_bytes方法buf传入错误，导致断言错误的问题
- 解决pipe潜在的写坏磁盘的问题
- 修复readdir中会读取到上一次脏数据的问题
=> 修复readdir以及读磁盘时buf传错问题

kernel/src/arch/x86_64/driver/apic/apic_timer.rs, kernel/src/common/time.h, kernel/src/process/mod.rs, kernel/src/process/resource.rs, kernel/src/process/syscall.rs, kernel/src/syscall/mod.rs, kernel/src/time/clocksource.rs, kernel/src/time/timekeeping.rs, kernel/src/time/timer.h, kernel/src/time/timer.rs
增加getrusage，并把apic timer的频率调整为系统HZ
=> 增加getrusage，并把apic timer的频率调整为系统HZ

kernel/src/arch/x86_64/syscall.rs, kernel/src/filesystem/vfs/file.rs, kernel/src/process/resource.rs, kernel/src/process/syscall.rs, kernel/src/syscall/mod.rs, user/apps/shell/cmd.c
添加prlimit64系统调用
注意: 目前仅支持读取默认的rlimit值,尚不支持设置rlimit值.
=> 添加prlimit64系统调用

kernel/src/arch/x86_64/driver/apic/apic.c, kernel/src/arch/x86_64/driver/apic/apic_timer.rs, kernel/src/arch/x86_64/driver/hpet.rs, kernel/src/arch/x86_64/driver/tsc.rs, kernel/src/arch/x86_64/ipc/signal.rs, kernel/src/arch/x86_64/process/mod.rs, kernel/src/arch/x86_64/syscall/mod.rs, kernel/src/driver/net/e1000e/e1000e_driver.rs, kernel/src/driver/net/virtio_net.rs, kernel/src/exception/softirq.rs, kernel/src/exception/trap.c, kernel/src/filesystem/procfs/mod.rs, kernel/src/ipc/signal.rs, kernel/src/ipc/signal_types.rs, kernel/src/libs/rwlock.rs, kernel/src/libs/wait_queue.rs, kernel/src/net/mod.rs, kernel/src/net/net_core.rs, kernel/src/net/socket.rs, kernel/src/process/exit.rs, kernel/src/process/fork.rs, kernel/src/process/kthread.rs, kernel/src/process/mod.rs, kernel/src/sched/cfs.rs, kernel/src/sched/core.rs, kernel/src/sched/rt.rs, kernel/src/time/timekeeping.rs, kernel/src/time/timer.rs
-     fix: 修复调度器,软中断,定时器,网络子系统的部分锁的使用不符合锁依赖安全规范的问题
-     fix: 修复创建pcb时内核栈爆栈的问题
-     把异常的trap gate改成intr gate
=> Patch fix sched and net lockdep error

kernel/src/arch/x86_64/init/main.c, kernel/src/driver/keyboard/mod.rs, kernel/src/driver/keyboard/ps2_keyboard.h
=> fix: 修复了ps2和tty初始化顺序的错误

kernel/src/driver/tty/tty_device.rs, kernel/src/process/mod.rs, tools/write_disk_image.sh
=> 修复tty的buf满时始终阻塞的问题

kernel/src/libs/cpumask.rs, kernel/src/libs/mod.rs
Linux的cpumask还有很多的比如集合的与或非操作等等，时间原因暂时没实现。
=> 添加简单的cpumask

kernel/src/filesystem/procfs/mod.rs, kernel/src/libs/cpumask.rs, kernel/src/smp/mod.rs, kernel/src/smp/syscall.rs, kernel/src/syscall/mod.rs, user/Makefile
目前没有用上pid参数，我还没在process子系统里面找到相关内容
=> 使nproc可以正确获取到cpu核心数

tools/bootstrap.sh, tools/grub_auto_install.sh
Tested on TencentOS Server 4.0 (Based on Centos8)
=> chore(tools): add bootstrap support for Centos/RHEL8/fedora

kernel/src/driver/tty/termios.rs, kernel/src/driver/tty/tty_port.rs, kernel/src/driver/tty/virtual_terminal/mod.rs, kernel/src/driver/tty/virtual_terminal/virtual_console.rs, kernel/src/driver/video/console/dummycon.rs, kernel/src/driver/video/console/mod.rs, kernel/src/driver/video/fbdev/base/fbcon/framebuffer_console.rs, kernel/src/driver/video/mod.rs, kernel/src/init/initial_kthread.rs
使得riscv能暂时完成stdio_init(将来需要实现riscv的串口console)
=> Feat(tty): add dummy console

kernel/src/arch/riscv64/pci/mod.rs, kernel/src/arch/x86_64/pci/pci.rs, kernel/src/driver/pci/pci.rs, kernel/src/driver/pci/pci_irq.rs, kernel/src/driver/virtio/transport_pci.rs
=> pci: 统一使用ecam root

kernel/src/arch/mod.rs, kernel/src/arch/riscv64/pci/mod.rs, kernel/src/arch/riscv64/pci/pci_host_ecam.rs, kernel/src/arch/x86_64/init/mod.rs, kernel/src/arch/x86_64/pci/pci.rs, kernel/src/driver/net/e1000e/e1000e.rs, kernel/src/driver/open_firmware/fdt.rs, kernel/src/driver/pci/ecam.rs, kernel/src/driver/pci/mod.rs, kernel/src/driver/pci/pci.rs, kernel/src/driver/pci/pci_irq.rs, kernel/src/driver/pci/root.rs, kernel/src/driver/virtio/transport_pci.rs, kernel/src/mm/mmio_buddy.rs, kernel/src/mm/page.rs, kernel/src/syscall/mod.rs
- pci: 添加pci root manager来管理pci root.
- pci: 使得riscv能够正常扫描pci设备.
=> pci: 添加pci root manager来管理pci root，并使得riscv能够正常扫描pci设备.

kernel/Cargo.toml, kernel/src/driver/virtio/transport_pci.rs
chore: Update virtio-drivers to commit 61ece509c4 and modify max_queue_size implementation
=> chore: Update virtio-drivers to commit 61ece509c4

kernel/Cargo.toml, kernel/src/arch/riscv64/mm/mod.rs, kernel/src/arch/riscv64/pci/mod.rs, kernel/src/driver/base/device/dd.rs, kernel/src/driver/base/device/mod.rs, kernel/src/driver/block/mod.rs, kernel/src/driver/block/virtio_blk.rs, kernel/src/driver/disk/ahci/ahcidisk.rs, kernel/src/driver/input/serio/serio_driver.rs, kernel/src/driver/net/virtio_net.rs, kernel/src/driver/open_firmware/fdt.rs, kernel/src/driver/timers/mod.rs, kernel/src/driver/virtio/mmio.rs, kernel/src/driver/virtio/mod.rs, kernel/src/driver/virtio/transport.rs, kernel/src/driver/virtio/transport_mmio.rs, kernel/src/driver/virtio/virtio.rs, kernel/src/driver/virtio/virtio_impl.rs, kernel/src/filesystem/mbr.rs, kernel/src/filesystem/vfs/core.rs, kernel/src/init/init.rs, kernel/src/init/initial_kthread.rs, kernel/src/libs/printk.rs, kernel/src/mm/mmio_buddy.rs, kernel/src/mm/page.rs, kernel/src/syscall/mod.rs, tools/run-qemu.sh
- feat(virtio): riscv: 添加virtio-blk driver,并在riscv下能够正确挂载FAT32
- feat(log): 添加custom logger以便打印依赖库的日志
=> feat(virtio): riscv: 添加virtio-blk driver,并在riscv下能够正确挂载FAT32

kernel/src/arch/riscv64/asm/csr.rs, kernel/src/arch/riscv64/cpu.rs, kernel/src/arch/riscv64/process/mod.rs, kernel/src/arch/riscv64/process/syscall.rs, kernel/src/arch/riscv64/smp/mod.rs, kernel/src/driver/acpi/pmtmr.rs, kernel/src/driver/clocksource/acpi_pm.rs, kernel/src/driver/clocksource/timer_riscv.rs, kernel/src/driver/disk/mod.rs, kernel/src/filesystem/vfs/core.rs, kernel/src/init/initial_kthread.rs
fix(riscv/process): 把riscv的调度时钟节拍率与HZ同步，并且修复切换到用户态的时候忘了在内核态关中断的bug
=> fix(riscv/process): 把riscv的调度时钟节拍率与HZ同步，并且修复切换到用户态的时候忘了在内核态关中断的bug

docs/conf.py
根据read the docs在7月15日blog,进行此修改
https://about.readthedocs.com/blog/2024/07/addons-by-default/
=> chore: 更新sphinx相关配置，适应read the docs的更新

kernel/src/driver/net/loopback.rs, kernel/src/driver/net/mod.rs, kernel/src/init/initial_kthread.rs, kernel/src/net/net_core.rs, kernel/src/net/syscall.rs, user/apps/test_lo/.gitignore, user/apps/test_lo/Cargo.toml, user/apps/test_lo/Makefile, user/apps/test_lo/README.md, user/apps/test_lo/src/main.rs, user/dadk/config/test_lo_0_1_0.dadk
#546 
- 添加lo设备及其驱动
- 实现本机127.0.0.1通信
=> feat(driver/net): 实现Loopback网卡接口

kernel/src/cgroup/cgroup.rs, kernel/src/cgroup/mod.rs, kernel/src/lib.rs, kernel/src/namespace/mod.rs, kernel/src/namespace/namespace.rs, kernel/src/namespace/pid_namespace.rs, kernel/src/namespace/ucount.rs, kernel/src/namespace/user_namespace.rs
[feat](namespace) add pid_namespace
主要实现了pid_namespace 以及和namespace 相关的数据结构，部分实现了user_namespace
=> [feat](namespace) add pid_namespace

kernel/Cargo.toml, kernel/crates/wait_queue_macros/Cargo.toml, kernel/crates/wait_queue_macros/src/lib.rs, kernel/src/arch/x86_64/interrupt/mod.rs, kernel/src/filesystem/vfs/file.rs, kernel/src/ipc/pipe.rs, kernel/src/ipc/signal.rs, kernel/src/ipc/signal_types.rs, kernel/src/lib.rs, kernel/src/libs/wait_queue.rs, kernel/src/mm/page.rs, kernel/src/process/kthread.rs, kernel/src/process/mod.rs, kernel/src/sched/fair.rs
修复了pipe等待的时候，没有处理信号，导致永远等待，kill不掉的问题
=> fix: pipe 读取/写入阻塞时,无法kill进程的问题

kernel/src/driver/pci/pci_irq.rs, kernel/src/init/initial_kthread.rs
修复存在多个virtio设备时，中断号冲突的问题
@ZZJJWarth 
https://bbs.dragonos.org.cn/t/topic/339
=> fix: 修复存在多个virtio设备时，中断号冲突的问题

kernel/src/cgroup/cgroup.rs, kernel/src/cgroup/mem_cgroup.rs, kernel/src/cgroup/mod.rs, kernel/src/libs/ida/src/lib.rs, kernel/src/namespace/mnt_namespace.rs, kernel/src/namespace/mod.rs, kernel/src/namespace/namespace.rs, kernel/src/namespace/pid_namespace.rs, kernel/src/namespace/ucount.rs, kernel/src/namespace/user_namespace.rs, kernel/src/process/mod.rs
1. 主要完善实现了pid_namespace
2. 基本实现了mnt_namespace 
3. 开始cgroup的架构设计
=> feat(namespace): add mnt_namespace 

Makefile
* remove --init suffix in update-submodules-by-mirror
fix #927
=> fix: Fix make update-submodules-by-mirror Error

user/dadk/config/nova_shell-0.1.0.dadk
[#49](https://github.com/DragonOS-Community/NovaShell/pull/49)
=> chore: Update NovaShell to 7bb802ad1e

tools/run-qemu.sh
**PR描述：**
修改了run-qemu.sh脚本，支持在无kvm模块加载的系统上运行DragonOS
=> fix(tools):支持在无kvm支持下运行DragonOS

kernel/src/filesystem/eventfd.rs
[issue:884](https://github.com/DragonOS-Community/DragonOS/issues/884)
=> fix:修复阻塞读取eventfd时无法被中断的bug

kernel/src/arch/x86_64/ipc/signal.rs
如果handle signal里面，默认处理函数是退出进程的话，会导致pcb永远无法释放
=> fix: do_signal函数在处理SIG_KILL时,有一处pcb强引用未归零的问题

kernel/src/driver/tty/tty_ldisc/ntty.rs, kernel/src/process/fork.rs, kernel/src/process/mod.rs
- 修复clone时未拷贝父进程tty的问题
- 修复tty处理信号时错误地将前台进程组置空的问题
=> 修复tty信号处理相关问题

kernel/src/ipc/pipe.rs, user/apps/test_fifo_write/Makefile, user/apps/test_fifo_write/main.c, user/dadk/config/test_fifo_write_0_1_0.toml
由于 https://github.com/DragonOS-Community/DragonOS/pull/1061 的合并点错了，我重置了master分支，现在重新把pr点上来。
原始信息及review请见： https://github.com/DragonOS-Community/DragonOS/pull/1061
=> fix:命名管道读行为不符合posix规范问题 

docs/kernel/net/index.rst, docs/kernel/net/inet.md
Add Internet protocol socket documents
=> feat(net): Add Internet protocol socket documents

kernel/src/namespaces/syscall.rs, kernel/src/net/socket/buffer.rs, kernel/src/net/socket/unix/seqpacket/inner.rs, kernel/src/net/socket/unix/seqpacket/mod.rs, kernel/src/net/socket/unix/stream/inner.rs, kernel/src/net/socket/unix/stream/mod.rs
=> feat:make fmt

kernel/Cargo.lock, kernel/Cargo.toml, kernel/Makefile, kernel/crates/intertrait/src/lib.rs, kernel/src/arch/riscv64/mod.rs, kernel/src/arch/riscv64/syscall/mod.rs, kernel/src/arch/x86_64/mod.rs, kernel/src/arch/x86_64/syscall/mod.rs, kernel/src/debug/kallsyms.c, kernel/src/debug/panic/hook.rs, kernel/src/debug/panic/mod.rs, kernel/src/debug/traceback/mod.rs, kernel/src/lib.rs, kernel/src/mm/allocator/kernel_allocator.rs, kernel/src/syscall/mod.rs
=> fix the panic error for riscv64

kernel/src/filesystem/poll.rs, kernel/src/ipc/signal.rs, kernel/src/ipc/signal_types.rs, kernel/src/ipc/syscall.rs, kernel/src/net/event_poll/mod.rs, kernel/src/process/mod.rs, kernel/src/syscall/mod.rs, kernel/src/time/mod.rs, user/apps/test_poll/.gitignore, user/apps/test_poll/Makefile, user/apps/test_poll/ppoll.c
- 新增ppoll系统调用，支持信号屏蔽和精确超时控制
- 优化poll系统调用，修复超时处理逻辑
- 新增ProcessControlBlock::has_pending_not_masked_signal方法，优化信号检测
- 添加Instant::saturating_sub方法，改进时间计算
- 新增rt_sigpending系统调用，支持获取待处理信号
- 添加ppoll测试程序，验证ppoll功能
=> feat: 实现ppoll系统调用并优化poll相关功能

kernel/Cargo.toml, kernel/src/driver/tty/tty_core.rs, kernel/src/driver/tty/tty_device.rs, kernel/src/filesystem/eventfd.rs, kernel/src/filesystem/vfs/file.rs, kernel/src/filesystem/vfs/mod.rs, kernel/src/filesystem/vfs/mount.rs, kernel/src/ipc/pipe.rs, kernel/src/net/event_poll/mod.rs, kernel/src/net/socket/mod.rs, kernel/src/perf/mod.rs, user/apps/syscall_ebpf/syscall_ebpf-ebpf/rust-toolchain.toml, user/apps/test_epoll/.gitignore, user/apps/test_epoll/Makefile, user/apps/test_epoll/main.c, user/dadk/config/test_epoll.toml
Add PollableInode trait
Implement PollableInode for pollable inodes
Fix #1094
=> refactor epoll related implementation

kernel/src/arch/x86_64/vm/vmx/mod.rs, kernel/src/init/init.rs
=> fix(boot): won't fail to boot when kvm not available

kernel/src/arch/loongarch64/filesystem/mod.rs, kernel/src/arch/loongarch64/filesystem/stat.rs, kernel/src/arch/loongarch64/mod.rs, kernel/src/arch/riscv64/filesystem/mod.rs, kernel/src/arch/riscv64/filesystem/stat.rs, kernel/src/arch/riscv64/mod.rs, kernel/src/arch/x86_64/filesystem/mod.rs, kernel/src/arch/x86_64/filesystem/stat.rs, kernel/src/arch/x86_64/mod.rs, kernel/src/driver/base/device/device_number.rs, kernel/src/filesystem/vfs/mod.rs, kernel/src/filesystem/vfs/stat.rs, kernel/src/filesystem/vfs/syscall.rs, kernel/src/syscall/mod.rs, user/apps/test_newfstatat/.gitignore, user/apps/test_newfstatat/Makefile, user/apps/test_newfstatat/main.c, user/dadk/config/test_newfstatat-0.1.0.toml
feat: 实现并测试 newfstatat 系统调用
新增了 newfstatat 系统调用的实现，并添加了相应的测试应用。同时，对文件系统相关代码进行了重构和优化。
=> feat: 实现并测试 newfstatat 系统调用

kernel/src/arch/x86_64/mm/fault.rs, kernel/src/mm/ucontext.rs, kernel/src/process/mod.rs, user/apps/test_stack/.gitignore, user/apps/test_stack/Makefile, user/apps/test_stack/main.c, user/dadk/config/test_stack_0_1_0.toml
Increase kernel stack to 32k. #1166 
Add guard pages below the user stack instead of above it.
Add a stack overflow test.
=> fix: Fix stack related errors

.github/workflows/doc_translation.yml
=> ci: 添加文档翻译的GitHub Actions工作流

kernel/src/driver/acpi/sysfs.rs
重构了ACPI表读取逻辑，使用宏定义表结构体并拆分读取函数以减少栈内存使用。
read函数的栈内存使用量从45369字节变成了小于4k
并且read往下的所有流程，峰值栈内存使用量也小于4k
=> refactor(driver/acpi): 重构ACPI表读取逻辑并优化栈内存使用

kernel/src/process/mod.rs
将`do_create_pcb()`的内存占用量从10k降低到5k
=> refactor: Optimize memory usage in do_create_pcb() from 10KB to 5KB

kernel/src/net/net_core.rs
原因是unified init导致网卡顺序不一样了,原本固定写死id的方式不对.现在改用名称匹配
=> fix(net): 解决dhcp偶尔失败的问题

.github/workflows/doc_translation.yml
- 减少MAX_WORKERS从20降到5
- 更换OPENAI_MODEL为hunyuan-turbos-latest
=> ci: 优化文档翻译工作流配置

README.md, README_CN.md
- 在README.md和README_CN.md中添加了腾讯云EdgeOne赞助商信息
- 新增CDN赞助商部分，包含EdgeOne标志和链接
=> docs: 添加腾讯云EdgeOne作为CDN赞助商
